[package]
name = "printerlib"
version = "0.1.0"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mystr = { path = "../mystr-1.0.0" }
